#!/usr/bin/env bash
# gen_certs.sh — bench PKI + credentials for the local Mosquitto test broker.
#
# Creates (in tools/broker/out/, gitignored):
#   ca.key / ca.crt          private CA (EC P-256), the only CA the device trusts
#   server.key / server.crt  broker cert, SAN = IP:<broker ip>, IP:127.0.0.1, DNS:localhost
#   passwd                   Mosquitto password file (device + server users)
#   creds.env                plaintext test credentials for the helper scripts
# and writes app/inc/conf_secrets.h (gitignored) with the CA PEM and the
# device's credentials.
#
# Usage: tools/broker/gen_certs.sh [broker_ip]      (default 192.168.0.100)
#        FORCE=1 tools/broker/gen_certs.sh          regenerate everything
#
# This is a bench CA. A production broker should use certificates from the
# operator's PKI; the firmware only needs the issuing CA in conf_secrets.h.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/out"
BROKER_IP="${1:-192.168.0.100}"
DEVICE_ID="$(sed -n 's/^#define NPS_DEVICE_ID[[:space:]]*"\(.*\)"/\1/p' "$ROOT/app/inc/conf_app.h")"
IMAGE="eclipse-mosquitto:2"

mkdir -p "$OUT"
cd "$OUT"

if [[ "${FORCE:-0}" == "1" ]]; then
    rm -f ca.* server.* passwd creds.env
fi

if [[ ! -f ca.crt ]]; then
    echo "### CA"
    openssl ecparam -name prime256v1 -genkey -noout -out ca.key
    openssl req -x509 -new -key ca.key -sha256 -days 3650 \
        -subj "/CN=NPS Bench CA" -out ca.crt
fi

if [[ ! -f server.crt ]]; then
    echo "### broker certificate for $BROKER_IP"
    openssl ecparam -name prime256v1 -genkey -noout -out server.key
    openssl req -new -key server.key -subj "/CN=$BROKER_IP" -out server.csr
    printf 'subjectAltName=IP:%s,IP:127.0.0.1,DNS:localhost\nextendedKeyUsage=serverAuth\n' \
        "$BROKER_IP" > server.ext
    openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
        -days 825 -sha256 -extfile server.ext -out server.crt
    rm -f server.csr server.ext
fi

if [[ ! -f creds.env ]]; then
    echo "### credentials"
    DEV_PASS="$(openssl rand -hex 16)"
    SRV_PASS="$(openssl rand -hex 16)"
    cat > creds.env <<EOF
DEVICE_ID=$DEVICE_ID
DEVICE_USER=$DEVICE_ID
DEVICE_PASS=$DEV_PASS
SERVER_USER=nps-server
SERVER_PASS=$SRV_PASS
BROKER_IP=$BROKER_IP
EOF
    rm -f passwd
    docker run --rm -u "$(id -u):$(id -g)" -v "$OUT:/m" "$IMAGE" \
        mosquitto_passwd -b -c /m/passwd "$DEVICE_ID" "$DEV_PASS"
    docker run --rm -u "$(id -u):$(id -g)" -v "$OUT:/m" "$IMAGE" \
        mosquitto_passwd -b /m/passwd nps-server "$SRV_PASS"
fi

# Mosquitto runs as uid 1883 inside the container and must read the key.
chmod 644 server.key passwd

# shellcheck disable=SC1091
source creds.env

echo "### app/inc/conf_secrets.h"
{
    echo "/* AUTO-GENERATED by tools/broker/gen_certs.sh — bench credentials, do not commit. */"
    echo "#ifndef APP_CONF_SECRETS_H_"
    echo "#define APP_CONF_SECRETS_H_"
    echo
    echo "#define NPS_MQTT_USER       \"$DEVICE_USER\""
    echo "#define NPS_MQTT_PASS       \"$DEVICE_PASS\""
    echo
    echo "#define NPS_BROKER_CA_PEM \\"
    sed 's/.*/    "&\\n" \\/' ca.crt
    echo
    echo "#endif /* APP_CONF_SECRETS_H_ */"
} > "$ROOT/app/inc/conf_secrets.h"

echo "### done: CA $(openssl x509 -in ca.crt -noout -fingerprint -sha256 | cut -d= -f2)"
